#!/usr/bin/env ruby

require_relative "ddnet-insta-cli/lib/strings"

# comments use YARD format
# https://rubydoc.info/gems/yard/file/docs/GettingStarted.md

class Gamemode
  def initialize(opts = {})
    @base_path = ["instagib"]

    # camel name of parent controller
    @parent_controller = "CGameControllerPvp"

    # never read this value directly
    # use the name_* getters
    @name = opts[:name].to_camel
  end

  # camel cased name
  def name
    @name
  end

  # @return [String] gamemode.h C++ source code
  def gen_cpp_header
    [
      include_guard_open,
      "",
      '#include "../base_pvp/base_pvp.h"',
      "",
      "class CGameController#{name} : public #{@parent_controller}",
      "{",
      "public:",
      "	CGameController#{name}(CGameContext *pGameServer);",
      "	~CGameController#{name}() override;",
      "",
      header_methods,
      "};",
      include_guard_close
    ].join("\n") + "\n"
  end

  # @return [String] gamemode.cpp C++ source code
  def gen_cpp_source
    ""
  end

  private

  def include_guard_open
    slug = @base_path.map(&:upcase).join('_')
    slug += '_' unless slug.empty?
    slug += name.to_snake.upcase
    [
      "#ifndef GAME_SERVER_GAMEMODES_#{slug}_H",
      "#define GAME_SERVER_GAMEMODES_#{slug}_H",
    ].join("\n")
  end

  def include_guard_close
    "#endif"
  end

  def header_methods
    [
      "void OnInit() override",
      "int OnCharacterDeath(class CCharacter *pVictim, class CPlayer *pKiller, int Weapon) override;",
    ].map { |m| "\t#{m}" }.join("\n")
  end
end

class Cli
  def initialize
    mode = Gamemode.new(
      name: 'placeholder'
    )
    puts mode.gen_cpp_header
  end
end

cli = Cli.new
