#!/usr/bin/env ruby

require_relative "ddnet-insta-cli/lib/strings"

# comments use YARD format
# https://rubydoc.info/gems/yard/file/docs/GettingStarted.md

class Controller
  @@pvp_controller = nil

  attr_reader :path

  def initialize(opts = {})
    # relative path from
    # src/game/server/gamemodes/
    @path = opts[:path] || ["instagib"]

    # class name
    @name = opts[:name].to_camel
    raise "Name can not be empty!" if @name.empty?

    # [String] filename base without extension
    @filename = opts[:filename].to_snake
    raise "Filename can not be empty!" if @filename.nil? || @filename.empty?
    raise "Invalid filename: #{@filename}" if @filename.include? '.'
  end

  # camel cased name
  def name
    @name
  end

  def name_snake
    @name.to_snake
  end

  # @return [String] controller header filename
  def header_filename
    "#{name_snake}.h"
  end

  # @return [String] controller cpp source filename
  def source_filename
    "#{name_snake}.cpp"
  end

  def self.pvp
    return @@pvp_controller if @@pvp_controller

    # TODO: omg all these values are so close!!!
    #       change the C++ code so we can do convention
    #       over configuration
    @@pvp_controller = Controller.new(
      path: 'base_pvp',
      name: 'pvp',
      filename: 'base_pvp',
    )
  end

  # TODO: create user facing dropdown with this
  #       so we can pick a parent controller
  def self.list
    {
      pvp: {
        controller: self.pvp,
        description: 'Basic pvp controller. Top recommendation!'
      }
    }
  end
end

class Gamemode
  def initialize(opts = {})
    opts[:filename] = opts[:name] if opts[:filename].nil?
    @controller = Controller.new(opts)

    # camel name of parent controller
    @parent_controller = Controller.pvp
  end

  # @return [String] gamemode.h C++ source code
  def gen_cpp_header
    [
      include_guard_open,
      "",
      '#include "../base_pvp/base_pvp.h"',
      "",
      "class CGameController#{@controller.name} : public CGameController#{@parent_controller.name}",
      "{",
      "public:",
      "	CGameController#{@controller.name}(CGameContext *pGameServer);",
      "	~CGameController#{@controller.name}() override;",
      "",
      header_methods,
      "};",
      include_guard_close
    ].join("\n") + "\n"
  end

  # @return [String] gamemode.cpp C++ source code
  def gen_cpp_source
    [
      "#include \"#{@controller.header_filename}.h\"",
      "",
      "#include <game/server/entities/character.h>",
      "#include <game/server/gamecontext.h>",
      "#include <game/server/player.h>",
      "",
      "class CGameController#{@controller.name} : public CGameController#{@parent_controller.name}"
    ].join("\n") + "\n"
  end

  private

  def include_guard_open
    slug = @controller.path.map(&:upcase).join('_')
    slug += '_' unless slug.empty?
    slug += @controller.name.to_snake.upcase
    [
      "#ifndef GAME_SERVER_GAMEMODES_#{slug}_H",
      "#define GAME_SERVER_GAMEMODES_#{slug}_H",
    ].join("\n")
  end

  def include_guard_close
    "#endif"
  end

  def header_methods
    [
      "void OnInit() override",
      "int OnCharacterDeath(class CCharacter *pVictim, class CPlayer *pKiller, int Weapon) override;",
    ].map { |m| "\t#{m}" }.join("\n")
  end
end

class Cli
  def initialize
    mode = Gamemode.new(
      name: 'placeholder'
    )
    puts mode.gen_cpp_header
  end
end

cli = Cli.new
